string = "ACCCAAGGCCGGCCCAAGGTTAATGGCCCAAGGCCCCAAGGTCCCAAGGGCCCAAGGCCCAAGGGAAACCCAAGGAGTAGACATTCTTCGCCCCAAGGGCCCCCAAGGATTCCCAAGGAGCCCAAGGCCCCAAGGATGCGCCCAAGGACCCAAGGCACCCCAAGGGAGGGTCACCCAAGGACCCAAGGGACCCAAGGACCCAAGGCGAACCCAAGGCCCAAGGGTCCCAAGGAAGGCCCAAGGCCCAAGGCACCCAAGGCCCCAAGGCCCAAGGACCGCCCAAGGCCCAAGGAAAACCCAAGGGCTACCCAAGGTGTCCCAAGGCCCAAGGCGCCCCAAGGCCCAAGGTCCCAAGGTGAGAACCCCAAGGGCTTCACACCCAAGGCCCAAGGCCCCCAAGGCAGCGACGTTCCTTCCCAAGGTTCCCAAGGTCCCAAGGGGGACCCAAGGCTTTCTAACAGGCCCCCAAGGGGTCCCAAGGCCTCCCAAGGTTCCCAAGGACGCCCAAGGTTAATCCCAAGGCCCAAGGCAGCAGTTCCCAAGGGCCCCAAGGTCCCAAGGCCCCAAGGCCCCAAGGCCCAAGGCCCAAGGGCCCAAGGCCCAAGGTCCCAAGGTCCCAAGGTCGTTGGTCCCAAGGACTCCCAAGGTACCCCAAGGATATCTCCCAAGGTCCCAAGGACCCCAAGGACGCCCAAGGACCCAAGGTACCCCAAGGGCCCAAGGCCCCCAAGGGCCCAAGGAGACTGGCCCAAGGTGATATTATTGACCCCAAGGCCCAAGGCCCAAGGCCGCCCAAGGTTACCCAAGGCCCAAGGACCCAAGGGCCCAAGGGACAACGCCCAAGGCACCCAAGGCCCAAGGTCCCAAGGGTTAAGACAAGCCCAAGGCTTATGCCCAAGGCCCAAGGGAGGAAGCACTTTAGGTCCCAAGGTGGCCCCAAGG"
sub = 'CCCAAGGCC'


def pattern_count(text, pattern):
    """This function will return the number of occurrences of a pattern in a string

    Args:
        text (string): The text that we want to find a pattern into
        pattern (string): The pattern

    Returns:
        int: The number of occurrences of the pattern in the text
    """
    count = 0
    for i in range(0, len(text) - len(pattern)+1):
        # print(text[i:i+len(pattern)])
        window = text[i:i+len(pattern)]
        if window == pattern:
            count += 1
    return count


if  __name__ == 'main' :
    print(pattern_count(string, sub))
